const token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
const guildID = "XXXXXXXXXXXXXXXXXXX";
const channelID_IDSync = "XXXXXXXXXXXXXXXXXXX";
const channelID_GPVerificationForum = "XXXXXXXXXXXXXXXXXXX";
const channelID_Webhook = "XXXXXXXXXXXXXXXXXXX"; 

const gitToken = "github_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
const gitGistID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

export { token, guildID, channelID_IDSync, channelID_GPVerificationForum, channelID_Webhook, gitToken, gitGistID }