services:
  ptcgp-reroll:
    build: .
    container_name: ptcgp-reroll
    restart: unless-stopped
    env_file: .env
    volumes: 
      - "/home/rvpi5/code/PTCGPRerollManager/data:/app/data"
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "500"
    command: ["node", "index.mjs"]
